name: CI/CD Pipeline

on: 
    push:
        branches:
            - main      # Trigger on pushes on the main branch
        tags:
            - 'v*.*.*'  # Trigger on version tags (e.g., v1.0.0)
    pull_request:
        branches:
            - main      # Trigger on pull requests to the main branch

        


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'
            
            - name: Install dependencies
              run: npm ci

            - name: Run lint
              run: npm run lint
            
            # - name: Run tests
            #   run: npm test

            - name: Build
              run: npm run build

            - name: Clear npm cache
              run: npm cache clean --force
      
            - name: Publish to npm
              if:  startsWith(github.ref, 'refs/tags/v')  # Publish only for version tags
              env:   
                NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}} # npm authentication token
              run: |
                echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
                npm config set @siemens:registry https://registry.npmjs.org/
                npm publish --access public